spring:
  application:
    name: producto-service
  cloud:
    consul:
      host: backend.fehler.gregoret.com.ar
      port: 8500
      discovery:
        ip-address: 10.128.0.2

  output.ansi.enabled: ALWAYS

#server:
#  port: 9002