spring:
  application:
    name: producto-service
  cloud:
    consul:
      host: 104.198.16.92
      port: 8500
      discovery:
        ip-address: fehler.gregoret.com.ar

  output.ansi.enabled: ALWAYS

server:
  port: 9002